### ISSUE TITLE
Argument text object

### ISSUE THREAD

**Issue by sassanh** [machakann/vim-swap#7] opened 2017-11-10 04:47 UTC
It would be great if vim-swap would provide argument text object like sideways.vim does.

**Comment by sassanh** [comment] 2017-11-10 04:56
The problem is I'm using `vim-angry` for argument text objects and I want a consistent experience when I swap arguments with vim-swap or I select them with vim-angry. To achieve it either vim-swap should provide argument text objects so that I can remove vim-angry and consider arguments to be what vim-swap defines them or vim-swap should use vim-angry.

Another issue is xml attributes (I was going to create a separate card for it, but now it's related to this card.) I would be great if I could swap xml attributes with vim-swap too (like sideways.vim partially supports.) I think it should work for jsx tag attributes too. I customized `vim-textobj-xmlattr` so that it supports jsx tag attributes so now I'm thinking about a feature in vim-swap that allows users to define backends for it. For example I configure vim-swap to use `ax` and `ix` (vim-textobj-xmlattr) and `aa` and `ia` (vim-angry) and now I can use vim-swap to swap xml attributes as defined in vim-textobj-xmlattr and arguments as defined in vim-angry.

**Comment by machakann** [comment] 2017-11-11 05:45
Hi, probably it is not so difficult to implement similar textobjects. I will work on it.

As for the xml attributes, I'm not clear about the language now. I need to check the specifications. It seems spaces are the delimiter for attributes, right?

**Comment by machakann** [comment] 2017-11-11 06:03
I'm not sure whether it is what you want or not, but so far the following rule works well to swap the attributes (, and would also work with textobjects in future).

```vim
let g:swap#rules  = deepcopy(g:swap#default_rules)
let g:swap#rules += [
      \   {'filetype': ['xml', 'jsx'],
      \    'surrounds': ['<?\?\h\w*\s*', '\s*[/?]\?>'],
      \    'delimiter': ['\_s\+'],
      \    'immutable': ['^\s\+'],
      \    'quotes': [['"', '"'], ["'", "'"]]},
      \ ]
```

**Comment by sassanh** [comment] 2017-11-11 06:13
It's much more complex for jsx, I give you a sample:
```
                                <input
                                    key='correct'
                                    style={{
                                        ...styles.numberField,
                                        width: '3em',
                                        direction: 'ltr',
                                        textAlign: 'right',
                                    }}
                                    value={(this.state.correct_coefficient || 0).persian()}
                                    onChange={({target: {value}}) => this.setState({'correct_coefficient': value.english()})}/>

```

As you see the delimiter is not space character, each attribute can potentially be a js dictionary, array, or even function (onChange attribute in example above).

There's a plugin for vim (`vim-textobj-xmlattr`) that I customized so that it can handle jsx attributes, this is my patch on the plugin:
```
-let s:RE_WORD = '\(\w\+\)'
+let s:RE_WORD = '\%(\w\+\)'
 " An attribute name: `src`, `data-attr`, `strange_attr`.
-let s:RE_ATTR_NAME = '\([a-zA-Z0-9\-_:@.]\+\)'
+let s:RE_ATTR_NAME = '\%([a-zA-Z0-9\-_:@.]\+\)'
 " A quoted string.
-let s:RE_QUOTED_STR = '\(".\{-}"\)'
+let s:RE_QUOTED_STR = '\%(".\{-}"\|''.\{-}''\)'
+" A js block (used in jsx files)
+let s:RE_JSX_BLOCK = '\%({\_.\{-}\%(}}\|}\)\%(\/>\|[ \n>]\)\@=\)'
 " The value of an attribute: a word with no quotes or a quoted string.
-let s:RE_ATTR_VALUE = '\(' . s:RE_QUOTED_STR . '\|' . s:RE_WORD . '\)'
+let s:RE_ATTR_VALUE = '\%(' . s:RE_QUOTED_STR . '\|' . s:RE_WORD . '\|' . s:RE_JSX_BLOCK . '\)'
 " The right-hand side of an XML attr: an optional `=something` or `="str"`.
-let s:RE_ATTR_RHS = '\(=' . s:RE_ATTR_VALUE . '\)\='
+let s:RE_ATTR_RHS = '\%(=' . s:RE_ATTR_VALUE . '\)\='

 " The final regex.
-let s:RE_ATTR_I = '\(' . s:RE_ATTR_NAME . s:RE_ATTR_RHS . '\)'
-let s:RE_ATTR_A = '\s\+' . s:RE_ATTR_I
+let s:RE_ATTR = '\%(' . s:RE_ATTR_NAME . s:RE_ATTR_RHS . '\)'
+let s:RE_ATTR_WITH_SPACE = '\%(\_s\+' . s:RE_ATTR . '\)'
+let s:RE_ATTR_I = '\(' . s:RE_ATTR . '\)'
+let s:RE_ATTR_A = '\(' . s:RE_ATTR_WITH_SPACE . '\)'
+" let s:RE_ATTR_I = '\%(<' . s:RE_ATTR_NAME . s:RE_ATTR_WITH_SPACE . '*\)\zs' . '\(' . s:RE_ATTR . '\)'
+" let s:RE_ATTR_A = '\%(<' . s:RE_ATTR_NAME . s:RE_ATTR_WITH_SPACE . '*\)\zs' . '\(' . s:RE_ATTR_WITH_SPACE . '\)'

 call textobj#user#plugin('xmlattr', {
 \   'attr-i': {
```
thought maybe it helps.

**Comment by machakann** [comment] 2017-11-11 07:02
oh, I found a strange bug...

**Comment by machakann** [comment] 2017-11-11 07:07
Thanks, your example is very helpful. 

The problem is currently the target text is split by using "delimiters", not by "items". It may be useful if we can split the text by "item" regular expressions instead of "delimiter" in this case. I may need to write another parser for achieving it. Let me think. 

Temporary, how about using this?
(I updated the example with  https://github.com/machakann/vim-swap/issues/7#issuecomment-343653555)
```vim
let s:RE_WORD = '\%(\w\+\)'
let s:RE_ATTR_NAME = '\%([a-zA-Z0-9\-_:@.]\+\)'
let s:RE_QUOTED_STR = '\%(".\{-}"\|''.\{-}''\)'
let s:RE_JSX_BLOCK = '\%({\_.\{-}\%(}}\|}\)\%(\/>\|[ \n>]\)\@=\)'
let s:RE_ATTR_VALUE = '\%(' . s:RE_QUOTED_STR . '\|' . s:RE_WORD . '\|' . s:RE_JSX_BLOCK . '\)'
let s:RE_ATTR_RHS = '\%(=' . s:RE_ATTR_VALUE . '\)\='
let s:RE_ATTR = '\%(' . s:RE_ATTR_NAME . s:RE_ATTR_RHS . '\)'
let s:RE_ATTR_WITH_SPACE = '\%(\_s*' . s:RE_ATTR . '\)'
let s:RE_ATTR_A = '\(' . s:RE_ATTR_WITH_SPACE . '\)'
let s:RE_JSX_TAG = '<?\?\h\w*\_s*\zs\%(' . s:RE_ATTR_WITH_SPACE . '\)*\ze\_s*/\?>'

let g:swap#rules  = deepcopy(g:swap#default_rules)
let g:swap#rules += [
      \   {'filetype': ['xml'],
      \    'surrounds': ['<?\?\h\w*\s*', '\s*[/?]\?>'],
      \    'delimiter': ['\_s\+'],
      \    'immutable': ['^\s\+'],
      \    'braket': [['{', '}']],
      \    'quotes': [['"', '"'], ["'", "'"]]},
      \   {'filetype': ['jsx'],
      \    'body': s:RE_JSX_TAG,
      \    'delimiter': ['\_s\+'],
      \    'immutable': ['^\s\+'],
      \    'braket': [['{', '}'], ['(', ')']],
      \    'quotes': [['"', '"'], ["'", "'"]]}
      \ ]
```

**Comment by sassanh** [comment] 2017-11-11 08:05
The temporary solution is good, it has problems as you know but it's really helpful and makes me able to use `vim-swap` for swapping not very complex attributes. thanks.

**Comment by sassanh** [comment] 2017-11-11 09:56
changing `RE_JSX_TAG` to solves some minor issues.
```
let s:RE_JSX_TAG = '<?\?\h\w*\_s*\zs\%(' . s:RE_ATTR_WITH_SPACE . '\)*\ze\_s*/\?>'
```

**Comment by machakann** [comment] 2017-11-11 10:29
Thanks, I updated the example.

**Comment by sassanh** [comment] 2017-11-11 11:17
This works in all situations I tried:
```
let g:swap#rules  = deepcopy(g:swap#default_rules)
let g:swap#rules += [
            \   {'filetype': ['xml'],
            \    'surrounds': ['<?\?\h\w*\_s*', '\_s*[/?]\?>'],
            \    'delimiter': ['\_s\+'],
            \    'immutable': ['^\s\+'],
            \    'braket': [['{', '}']],
            \    'quotes': [['"', '"'], ["'", "'"]]},
            \   {'filetype': ['jsx'],
            \    'surrounds': ['<\h\w*\ze\_s*' . s:RE_ATTR_WITH_SPACE, s:RE_ATTR_WITH_SPACE . '\_s*\zs[/?]\?>', 0],
            \    'delimiter': ['\_s\+'],
            \    'immutable': ['^\s\+'],
            \    'braket': [['{', '}']],
            \    'quotes': [['"', '"'], ["'", "'"]]}
            \ ]
```
There's only one problem though: it detects a false zero length attribute before first attribute, to solve it we should change `'<\h\w*\ze\_s*' . s:RE_ATTR_WITH_SPACE` to `'<\h\w*\_s*\ze' . s:RE_ATTR_WITH_SPACE` as I suggested in previous comment but this change ruins behavior for tags with only one attribute.

**Comment by machakann** [comment] 2017-11-15 14:12
This empty item is do required in some cases, thus I cannot remove. How about this?

```vim
let g:swap#rules += [
            \   {'filetype': ['jsx'],
            \    'surrounds': ['<\h\w*\_s*\ze' . s:RE_ATTR, s:RE_ATTR_WITH_SPACE . '\zs\_s*[/?]\?>', 0],
            \    'delimiter': ['\_s\+'],
            \    'immutable': ['^\s\+'],
            \    'braket': [['{', '}']],
            \    'quotes': [['"', '"'], ["'", "'"]]}
            \ ]
```

...but I found that it cannot start swap-mode on the first tag name (`input` in the above case). I will fix this.

**Comment by machakann** [comment] 2017-11-17 15:24
I fixed the above bug and added textobjects. You can use like this.

```vim
omap ia <Plug>(swap-textobject-i)
xmap ia <Plug>(swap-textobject-i)
omap aa <Plug>(swap-textobject-a)
xmap aa <Plug>(swap-textobject-a)
```

**Comment by sassanh** [comment] 2017-11-17 16:02
Great, I'll disable my current arg text object plugin and try above mappings for a while and will write my feedback here. Thanks.

**Comment by sassanh** [comment] 2017-11-18 06:51
In a js file I have:
```
const t = [
    1,
    2,
    3,
];
```
When my cursor is over "1" and I press `vaa` I get:

```
Error detected while processing function swap#textobj#select:
line    4:
E716: Key not present in Dictionary: items)
E116: Invalid arguments for function empty
E15: Invalid expression: empty(buffer.items)
```
It works for single line expressions but not for multi line expressions, for multiline expressions it either gives the above error or selects the whole body, not the argument.

**Comment by machakann** [comment] 2017-11-18 09:19
Thank you, I fix a bug. But I could not reproduce the case selecting the whole body. If you find the same situation, could you teach me your settings for vim-swap.

**Comment by sassanh** [comment] 2017-11-18 16:03
It seems to work perfect now. I tested many situations and it passed all tests. I guess we can close it. Thank you.

**Comment by machakann** [comment] 2017-11-19 03:06
Good news. I also pushed some small commits, it might solve. I will close this issue but feel free to tell any problem again.

**Closed as completed by machakann** 2017-11-19 03:06 UTC
